name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: '3.5'
            toxenv: py35
          - python-version: '3.6'
            toxenv: py36
          - python-version: '3.7'
            toxenv: py37
          - python-version: '3.8'
            toxenv: py38
          - python-version: '3.9'
            toxenv: py39
          - python-version: '3.10'
            toxenv: py310,lint,pytype
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox
      - name: tox
        run: tox
        env:
          TOXENV: ${{ matrix.toxenv }}
      